/**
 * webtape install — registers the Native Messaging host with Chrome/Edge/Brave
 * and opens the Chrome Web Store page for the extension.
 *
 * The host manifest is written to the OS-specific NativeMessagingHosts directory.
 * After installation, Chrome will spawn the webtape binary on-demand whenever
 * the extension calls chrome.runtime.connectNative('com.webtape.receiver').
 */

import { writeFileSync, mkdirSync, existsSync, chmodSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir, platform } from 'node:os';
import { execSync, execFile } from 'node:child_process';
import chalk from 'chalk';
import { stripExtensionIdFromSavedConfig } from './config.js';

export const HOST_NAME = 'com.webtape.receiver';

/**
 * 与 `packages/webtape-recorder/manifest.json` 中 `key` 对应的扩展 ID，
 * 开发解压加载与 Chrome 网上应用店发行一致，勿随意更改。
 */
export const WEBTAPE_EXTENSION_ID = 'jcbbpjhckcknopggkbafcjnnhddjpfhm';

/** Chrome 网上应用店（上架后可用；未上架时页面可能暂不可用） */
export const CWS_URL = `https://chromewebstore.google.com/detail/webtape/${WEBTAPE_EXTENSION_ID}`;

/**
 * Paths where Chrome (and Chromium-family browsers) look for NativeMessagingHosts
 * on each OS.
 */
function getNativeMessagingDirs(): { label: string; path: string }[] {
  const os = platform();
  const home = homedir();

  if (os === 'darwin') {
    return [
      {
        label: 'Chrome',
        path: join(home, 'Library', 'Application Support', 'Google', 'Chrome', 'NativeMessagingHosts'),
      },
      {
        label: 'Chromium',
        path: join(home, 'Library', 'Application Support', 'Chromium', 'NativeMessagingHosts'),
      },
      {
        label: 'Brave',
        path: join(home, 'Library', 'Application Support', 'BraveSoftware', 'Brave-Browser', 'NativeMessagingHosts'),
      },
      {
        label: 'Edge',
        path: join(home, 'Library', 'Application Support', 'Microsoft Edge', 'NativeMessagingHosts'),
      },
    ];
  }

  if (os === 'linux') {
    return [
      {
        label: 'Chrome',
        path: join(home, '.config', 'google-chrome', 'NativeMessagingHosts'),
      },
      {
        label: 'Chromium',
        path: join(home, '.config', 'chromium', 'NativeMessagingHosts'),
      },
      {
        label: 'Brave',
        path: join(home, '.config', 'BraveSoftware', 'Brave-Browser', 'NativeMessagingHosts'),
      },
      {
        label: 'Edge',
        path: join(home, '.config', 'microsoft-edge', 'NativeMessagingHosts'),
      },
    ];
  }

  if (os === 'win32') {
    // On Windows, registration goes to the registry; we write a helper manifest
    // to APPDATA and then set the registry key.
    return [
      {
        label: 'Windows (APPDATA)',
        path: join(process.env.APPDATA ?? join(home, 'AppData', 'Roaming'), 'WebTape', 'NativeMessagingHosts'),
      },
    ];
  }

  return [];
}

const CONFIG_DIR = join(homedir(), '.webtape-receiver');

/**
 * Single-quote a string for safe use in POSIX shell scripts.
 */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

/**
 * Create a wrapper shell script that invokes Node.js with absolute paths.
 *
 * WHY THIS IS NECESSARY:
 *   Chrome and other Chromium-family browsers are GUI applications launched
 *   by launchd on macOS (or the display manager on Linux). They inherit only
 *   the minimal system PATH from /etc/paths — typically just:
 *     /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
 *   User-level package managers (nvm, fnm, volta, homebrew cask, etc.) install
 *   Node.js in directories that are NOT in this system PATH. As a result, the
 *   shebang #!/usr/bin/env node in dist/index.js silently fails with
 *   "env: node: No such file or directory", and Chrome reports
 *   "Native host has exited." immediately after the connection attempt.
 *
 *   The fix is to generate a wrapper .sh script at install time that hardcodes
 *   the absolute path to the Node.js binary (process.execPath) and the absolute
 *   path to the main script. The native messaging manifest points to this
 *   wrapper, bypassing PATH resolution entirely.
 *
 * @returns Absolute path to the generated wrapper script.
 */
function createWrapperScript(): string {
  const nodeBinary = process.execPath;
  // import.meta.url for compiled dist/install.js → resolve index.js in same dir
  const scriptPath = fileURLToPath(new URL('./index.js', import.meta.url));

  const content = [
    '#!/bin/sh',
    '# Auto-generated by webtape install — do not edit manually.',
    '# Re-run "webtape install" after upgrading Node.js.',
    `exec ${shellQuote(nodeBinary)} ${shellQuote(scriptPath)} "$@"`,
    '',
  ].join('\n');

  mkdirSync(CONFIG_DIR, { recursive: true });
  const wrapperPath = join(CONFIG_DIR, 'host.sh');
  writeFileSync(wrapperPath, content, { encoding: 'utf-8' });
  chmodSync(wrapperPath, 0o755);
  return wrapperPath;
}

/**
 * Resolve the absolute path to the webtape executable for use in the manifest.
 * On macOS/Linux a wrapper shell script is generated so Chrome (a GUI app with
 * a restricted PATH) can locate the Node.js binary regardless of how it was
 * installed (nvm, fnm, volta, Homebrew, system package manager, etc.).
 */
function resolveExecutablePath(): string {
  const os = platform();

  if (os === 'darwin' || os === 'linux') {
    return createWrapperScript();
  }

  // Windows: Node is typically in the system PATH; use the bin wrapper script.
  try {
    const result = execSync('which webtape', { encoding: 'utf-8' }).trim();
    if (result && existsSync(result)) return result;
  } catch {
    // fall through
  }
  return process.argv[1];
}

/**
 * Build the Native Messaging host manifest JSON.
 */
function buildManifest(executablePath: string, extensionId: string): object {
  const os = platform();

  if (os === 'win32') {
    return {
      name: HOST_NAME,
      description: 'WebTape Native Messaging Host',
      path: executablePath,
      type: 'stdio',
      allowed_origins: [`chrome-extension://${extensionId}/`],
    };
  }

  return {
    name: HOST_NAME,
    description: 'WebTape Native Messaging Host',
    path: executablePath,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${extensionId}/`],
  };
}

function writeWindowsRegistry(manifestPath: string): void {
  try {
    execSync(
      `reg add "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${HOST_NAME}" /ve /d "${manifestPath}" /f`,
      { stdio: 'ignore' },
    );
    console.log(chalk.green('    ✓ Chrome (Registry)'));
  } catch {
    console.log(chalk.yellow('    ⚠ 无法写入 Chrome 注册表，请手动添加'));
  }
  try {
    execSync(
      `reg add "HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\${HOST_NAME}" /ve /d "${manifestPath}" /f`,
      { stdio: 'ignore' },
    );
    console.log(chalk.green('    ✓ Edge (Registry)'));
  } catch {
    // Edge is optional
  }
}

function openUrl(url: string): void {
  const os = platform();
  try {
    if (os === 'darwin') execFile('open', [url]);
    else if (os === 'win32') execFile('cmd', ['/c', 'start', '', url]);
    else execFile('xdg-open', [url]);
  } catch {
    // Best effort
  }
}

export interface InstallOptions {
  openStore?: boolean;
}

export async function runInstall(opts: InstallOptions = {}): Promise<void> {
  console.log('');
  console.log(chalk.bold.cyan('  🔧 WebTape — 安装 Native Messaging Host'));
  console.log(chalk.gray('  ─────────────────────────────────────────'));
  console.log('');

  stripExtensionIdFromSavedConfig();

  const extensionId = WEBTAPE_EXTENSION_ID;

  const executablePath = resolveExecutablePath();
  const manifest = buildManifest(executablePath, extensionId);
  const manifestJson = JSON.stringify(manifest, null, 2);
  const os = platform();

  console.log(`  ${chalk.green('可执行文件')}  ${executablePath}`);
  console.log(`  ${chalk.green('扩展 ID')}    ${extensionId}`);
  console.log('');

  const dirs = getNativeMessagingDirs();

  if (os === 'win32') {
    // On Windows: write a single manifest file and register in the registry
    const winDir = dirs[0].path;
    mkdirSync(winDir, { recursive: true });
    const manifestPath = join(winDir, `${HOST_NAME}.json`);
    writeFileSync(manifestPath, manifestJson, 'utf-8');
    console.log(chalk.green(`  ✓ 已写入 manifest → ${manifestPath}`));
    console.log('');
    console.log('  正在写入 Windows 注册表…');
    writeWindowsRegistry(manifestPath);
  } else {
    console.log('  正在写入 NativeMessagingHosts manifest…');
    console.log('');
    for (const dir of dirs) {
      try {
        mkdirSync(dir.path, { recursive: true });
        const manifestPath = join(dir.path, `${HOST_NAME}.json`);
        writeFileSync(manifestPath, manifestJson, 'utf-8');
        console.log(chalk.green(`    ✓ ${dir.label}: ${manifestPath}`));
      } catch (err) {
        console.log(chalk.gray(`    - ${dir.label}: 跳过 (${(err as Error).message})`));
      }
    }

    // Ensure the executable is executable
    try {
      chmodSync(executablePath, 0o755);
    } catch {
      // ignore
    }
  }

  console.log('');
  console.log(chalk.green('  ✅ Native Messaging Host 注册完成'));
  console.log('');

  if (opts.openStore !== false) {
    console.log(chalk.cyan('  正在打开 Chrome 插件安装页…'));
    openUrl(CWS_URL);
    console.log(chalk.gray('  请在浏览器中点击"添加到 Chrome"完成插件安装。'));
    console.log('');
    console.log(chalk.gray('  提示：如果浏览器没有自动打开，请手动访问:'));
    console.log(chalk.cyan(`  ${CWS_URL}`));
  }

  console.log('');
  console.log(chalk.bold('  安装完成！'));
  console.log(chalk.gray('  录制时直接点击插件图标，无需任何额外操作。'));
  console.log('');
}
